import fs from 'node:fs';

const pantryRows = [
  ['Clementines','4'],['Gluten-free food box','1 box'],['Philadelphia cream cheese','2 tubs'],['Branston small chunk pickle','1 jar'],['Alpro single soya cream','1 carton'],['Alpro oat milk','1 carton'],['Coca-Cola Zero Sugar','1 bottle'],['Yeo Valley organic whole milk','1 carton'],['Flora buttery spread','1 tub'],['Hummus','1 tub'],['Scottish mussels','1 pack'],['Grapes (punnet)','1 punnet'],['Strawberries (punnet)','1 punnet'],['Eggs','6'],['Wine bottle','2 bottles'],['Birra Angelo Poretti beer','1 pack'],['Indian tonic water','1 pack'],['Orange juice','1 carton'],['Mayonnaise','1 jar'],['Ketchup','2 bottles'],['Barbecue sauce','1 bottle'],['Hot sauce','1 bottle'],['Salad dressing','1 bottle'],['Raspberry jam','1 jar'],['Jam or preserve (unlabelled jar)','2 jars'],['Baby food pouch','1'],['Yoghurt pot','1'],['Yoghurt multipack','1'],['Cheese (wrapped)','2 packs'],['Cooked sliced meat (pack)','1 pack'],['Prepared food container','3 containers'],['Wraps or flatbreads (pack)','1 pack'],['Milk carton','1 carton'],['Frozen peas','1 bag'],['Frozen spinach','1 bag'],['Frozen vegetables (bag)','1 bag'],['Frozen breaded fish portions','1 bag'],['Frozen chips','1 bag'],['Frozen chicken pieces','1 bag'],['Frozen mixed berries','1 bag'],['Frozen chopped onions','1 bag'],['Frozen ready meal','2'],['Vanilla ice cream','1 tub'],['Waffle ice-cream cones','1 pack'],['Tinned mackerel','3 tins'],['Tinned baked beans','2 tins'],['Tinned tomatoes','6 tins'],['Tinned coconut milk','1 tin'],['Tinned tuna','2 tins'],['Tinned fish (other)','2 tins'],['Tinned food (unidentified)','5 tins'],['Pasta (dryassorted bags)','1 bag'],['Lasagne sheets','1 pack'],['Rice (bag)','1 bag'],['Instant mashed potato','1 pack'],['Couscous or grain packet','1 pack'],['Sugar','1 pack'],['Salt','1 pack'],['Light soy sauce','1 bottle'],['Piccalilli','1 jar'],['Crunchy peanut butter','1 jar'],['Smooth peanut butter','1 jar'],['Tahini','1 jar'],['Balsamic vinegar','1 bottle'],['Red wine vinegar','1 bottle'],['Apple cider vinegar','1 bottle'],['Cooking oil','2 bottles'],['Belvita breakfast biscuits','1 pack'],['Oreo cocoa biscuits','1 pack'],['Nissin instant noodles','1 pack'],['Crackers','2 packs'],['Chocolate spread','1 jar'],['Fruit tea (box)','1 box'],['Spices or seasoning packets','3 packets']
];

const fresh = new Set(['Clementines','Grapes (punnet)','Strawberries (punnet)','Scottish mussels']);
const chilled = new Set(['Philadelphia cream cheese','Alpro single soya cream','Alpro oat milk','Yeo Valley organic whole milk','Flora buttery spread','Hummus','Eggs','Orange juice','Mayonnaise','Salad dressing','Baby food pouch','Yoghurt pot','Yoghurt multipack','Cheese (wrapped)','Cooked sliced meat (pack)','Wraps or flatbreads (pack)','Milk carton','Prepared food container']);
const frozen = new Set(pantryRows.map(x=>x[0]).filter(x=>x.startsWith('Frozen ') || ['Vanilla ice cream','Waffle ice-cream cones'].includes(x)));
const pantry_inventory = pantryRows.map(([item,quantity]) => ({
  item, quantity,
  use_by_date: fresh.has(item) ? '2026-09-13' : chilled.has(item) ? '2026-09-17' : frozen.has(item) ? '2026-12-31' : '2027-09-10'
}));

const meal = (name, servings, prep, cook, difficulty, notes) => ({meal:name,servings,prep_time_minutes:prep,cook_time_minutes:cook,difficulty,notes});
const days = [
  {date:'2026-09-11',day:'Friday',breakfast:meal('Toast with jam or peanut butter, strawberries and grapes',4,5,3,'easy','Uses the most delicate pantry fruit first. Use the existing wraps toasted if no bread is open.'),lunch:meal('Ham and cream-cheese wraps with hummus and clementines',4,10,0,'easy','Uses the existing sliced meat, wraps, cream cheese and hummus early. Keep one clementine back if needed for a later snack.'),dinner:meal('Scottish mussels with chips, peas and bread',4,10,15,'medium','Use the pantry mussels on the first day because they are the most time-sensitive item. Serve the existing frozen chips and peas; discard any mussels that do not open after cooking.'),snacks:['Strawberries and grapes','Existing yoghurt','Crackers with cream cheese']},
  {date:'2026-09-12',day:'Saturday',breakfast:meal('Pancakes with mixed-berry compote',4,10,15,'easy','Uses four pantry eggs and existing frozen berries. Make a double stack only if there is freezer space; cooked pancakes freeze well.'),lunch:meal('Mackerel and vegetable rice',4,10,10,'easy','Uses two pantry tins of mackerel, pantry rice and frozen vegetables, avoiding another fresh protein purchase.'),dinner:meal('Chicken fajita wraps with fresh salsa',4,20,20,'medium','Cook while lettuce and peppers are fresh. Use the pantry frozen chicken pieces, wraps and seasonings. Make salsa during the afternoon preparation session.'),snacks:['Fresh banana bread','Clementines','Oat-raisin cookies']},
  {date:'2026-09-13',day:'Sunday',breakfast:meal('Ready Break with soy milk and banana',4,5,3,'easy','A quick breakfast before the roast. Slice only the bananas needed so the rest remain available for banana bread and snacks.'),lunch:meal('Beans on toast with grated cheese',4,5,8,'easy','Uses one pantry tin of beans and existing cheese. Freeze half the new loaf on shopping day so it stays fresh for later lunches.'),dinner:meal('Roast chicken dinner with roast potatoes, carrots, broccoli and peas',4,20,75,'hard','Roast a chicken large enough to leave about 500 g cooked meat. Cool leftovers promptly: reserve for Monday and Tuesday lunches, and freeze Tuesday’s portion if not using within 48 hours.'),snacks:['Banana bread','Apple slices with peanut butter','Yoghurt']},
  {date:'2026-09-14',day:'Monday',breakfast:meal('Cereal with soy milk and blueberries',4,5,0,'easy','Opens the purchased blueberries early in the week. Use pantry oat milk first if the soy milk is not yet needed elsewhere.'),lunch:meal('Leftover roast chicken mayonnaise sandwiches',4,10,0,'easy','Uses reserved roast chicken and existing mayonnaise. Add leftover lettuce from fajitas to prevent waste.'),dinner:meal('Spaghetti Bolognese with carrot, celery and onion',4,20,60,'medium','Carrot and celery keep well after the weekend. Make six portions: serve four and chill or freeze two for Thursday lunch.'),snacks:['Blueberries','Oat-raisin cookies','Crisps']},
  {date:'2026-09-15',day:'Tuesday',breakfast:meal('Toast with peanut butter and banana',4,5,3,'easy','Uses ripe bananas and pantry peanut butter. Take bread from the freezer the night before.'),lunch:meal('Chicken mayonnaise wraps or sandwiches',4,10,0,'easy','Uses the final safely stored roast chicken. If there is less than four portions, supplement with one pantry tin of tuna.'),dinner:meal('Salmon, potato wedges and broccoli',4,10,45,'easy','Freeze the salmon on shopping day and thaw overnight Monday; this lets the plan use fragile salad produce first without risking the fish.'),snacks:['Banana bread','Raisins','Cheddars']},
  {date:'2026-09-16',day:'Wednesday',breakfast:meal('Ready Break with soy milk and mixed berries',4,5,3,'easy','Frozen berries give variety without adding late-week fresh-fruit waste.'),lunch:meal('Leek, potato and carrot soup with bread',4,15,30,'medium','Uses the remaining celery, carrots and potatoes. Make six portions and freeze two for an easy future lunch.'),dinner:meal('Jacket potatoes with tuna, cheese and beans',4,10,60,'easy','Uses pantry tuna, beans and cheese. Bake four medium-large potatoes; any extra filling can top Thursday toast.'),snacks:['Apple','Fruit lolly','Oat-raisin cookies']},
  {date:'2026-09-17',day:'Thursday',breakfast:meal('Cereal with soy milk and banana',4,5,0,'easy','Finishes opened cereal, soy milk and remaining ripe banana near the end of the plan.'),lunch:meal('Leftover Spaghetti Bolognese',2,5,5,'easy','Use the two extra portions made Monday. The other two people can use pantry ready meals or soup portions if four lunches are required.'),dinner:meal('Fish fingers, chips, peas and beans',4,10,25,'easy','A freezer-led final dinner prevents late-week spoilage and uses pantry breaded fish, chips, peas and the remaining tin of beans.'),snacks:['Satsumas or remaining clementines','Biscuits','Ice cream']}
];

const weekly_preparations = [
  {name:'Dairy-free banana bread',prep_day:'Saturday',yield:'1 loaf, approximately 10 slices',storage:'Keep 3 days airtight; freeze remaining slices for up to 3 months.',used_for:['Saturday snack','Sunday snack','Tuesday snack'],notes:'Use 3 very ripe bananas, 250 g self-raising flour, 100 g sugar, 2 eggs, 75 ml oil and a little soy milk. Pantry eggs, sugar and oil reduce the purchase requirement.'},
  {name:'Fresh tomato salsa',prep_day:'Saturday',yield:'About 400 g / 1 medium bowl',storage:'Refrigerate covered and use within 2 days.',used_for:['Saturday chicken fajita wraps'],notes:'Prepare shortly before dinner from tomatoes, onion, lime and optional hot sauce. Make only one bowl because fresh salsa does not keep well.'},
  {name:'Dairy-free oat and raisin cookies',prep_day:'Saturday',yield:'Approximately 18 cookies',storage:'Airtight for 5 days; freeze baked cookies for up to 2 months.',used_for:['Saturday snack','Monday snack','Wednesday snack'],notes:'Use pantry sugar, oil and raisins purchased as snacks; oats and flour are shared with breakfasts and banana bread. Freeze half immediately to control waste.'}
];

const item = (category,name,quantity,used_for,notes,aisle,price,perishable=false,needs_freezing=false,bulkrecommend='') => ({category,item:name,quantity,used_for,notes,bulkrecommend,aisle,estimated_price:price,purchased:false,perishable,needs_freezing});
const shopping_list = [
  item('Produce','Bananas','7 medium',['Breakfasts','Banana bread'],'Buy a small loose quantity rather than a large bag; three should become ripe for Saturday prep.','produce',2,true,false,''),
  item('Produce','Apples','1 pack of 6',['Snacks'],'A six-pack covers several snacks without overbuying.','produce',2,true,false,''),
  item('Produce','Blueberries','1 small punnet',['Monday breakfast'],'Use early after opening. Existing strawberries and grapes cover the first days.','produce',3,true,false,''),
  item('Produce','Satsumas','1 small pack',['Thursday snack'],'You already have 4 clementines; delay opening this pack until those are used.','produce',2,true,false,''),
  item('Produce','Lettuce','1 small head or 2-pack little gem',['Fajitas','Chicken sandwiches'],'Use across Saturday and Monday. Avoid a large iceberg if only large sizes are available.','produce',1.2,true,false,''),
  item('Produce','Bell peppers','3-pack',['Chicken fajitas'],'Use all three in Saturday dinner; leftovers can go into Monday Bolognese.','produce',1.8,true,false,''),
  item('Produce','Fresh tomatoes','6 medium',['Fresh salsa'],'Purchase loose to match the salsa batch. You already have 6 tinned tomatoes, so no tins are needed.','produce',1.8,true,false,''),
  item('Produce','Lime','1',['Fresh salsa'],'One lime is sufficient for the weekly salsa.','produce',0.35,true,false,''),
  item('Produce','Carrots','1 kg bag',['Roast dinner','Bolognese','Soup'],'Shared across three dishes; a standard 1 kg bag should be nearly fully used.','produce',0.75,true,false,''),
  item('Produce','Celery','1 head',['Bolognese','Soup'],'Use several sticks Monday and the remainder in Wednesday soup; freeze chopped excess.','produce',0.8,true,true,'Chopped celery can be frozen for roughly 3 months for soups and sauces.'),
  item('Produce','Fresh onions','3 medium',['Salsa','Roast dinner','Bolognese'],'You already have frozen chopped onions for stir-ins; buy only three fresh where texture matters.','produce',0.75,true,false,''),
  item('Produce','Potatoes','2.5 kg bag',['Roast dinner','Salmon dinner','Jacket potatoes','Soup'],'One standard bag covers all four uses and minimises part-bag waste. Store cool and dark.','produce',2.5,true,false,'A 2.5 kg bag should last this week; larger sacks are only worthwhile if stored cool, dark and dry.'),
  item('Produce','Broccoli','2 heads',['Roast dinner','Salmon dinner'],'Use one Sunday and one Tuesday. Frozen vegetables already cover other meals.','produce',1.6,true,false,''),
  item('Produce','Leeks','2 medium',['Soup'],'Sized for one six-portion soup batch.','produce',1.2,true,false,''),
  item('Bakery','Seeded bread','2 loaves',['Toast breakfasts','Sunday lunch','Chicken sandwiches','Soup'],'Freeze one loaf immediately and take slices as needed. Existing wraps cover Friday and fajitas.','bakery',4,true,true,'Bread multipacks are economical only with freezer space; frozen sliced bread keeps about 3 months.'),
  item('Breakfast','Ready Break or smooth porridge oats','1 medium box',['Saturday and Wednesday breakfasts'],'The workbook lists Ready Break; one box will last beyond this plan.','cereal',3,false,false,'A medium box should cover several weeks at two breakfasts per week; keep airtight.'),
  item('Breakfast','Cereal','1 family box',['Monday and Thursday breakfasts'],'Choose one cereal the household already likes to avoid an unfinished second box.','cereal',3,false,false,'A family box should last about 2 weeks at the planned rate if kept sealed.'),
  item('Baking','Self-raising flour','1.5 kg bag',['Pancakes','Banana bread','Cookies'],'Shared by all three preparations.','baking',2,false,false,'A 1.5 kg bag should last 3–5 weeks at this plan frequency; store airtight.'),
  item('Baking','Oats','1 kg bag',['Oat-raisin cookies'],'Also useful if Ready Break runs out.','cereal',2,false,false,'A 1 kg bag can last 4–6 weeks and is suitable for bulk purchase when stored airtight.'),
  item('Baking','Raisins','1 six-pack or 300 g bag',['Snacks','Oat-raisin cookies'],'Use part in cookies and retain the rest as portioned snacks.','dried fruit',2,false,false,'A resealable 300–500 g bag is cheaper than snack packs and lasts several weeks.'),
  item('Dairy alternatives','Soy milk','2 x 1 litre cartons',['Pancakes','Ready Break','Cereal','Banana bread'],'The plan requires soy milk. You already have one Alpro oat milk carton, but it is not a soy substitute where soy is required.','dairy alternatives',4,true,false,'UHT multipacks can be bulk bought and usually keep for months unopened; once opened, follow the pack and refrigerate.'),
  item('Meat','Whole chicken','1 chicken, approximately 2 kg',['Sunday roast','Monday lunch','Tuesday lunch'],'Choose about 2 kg to provide four roast portions plus roughly 500 g leftovers. Freeze on purchase if the use-by date is before Sunday.','meat',7,true,false,'Whole chickens can be bought on promotion and frozen for up to roughly 9–12 months; thaw fully in the fridge.'),
  item('Fish','Salmon fillets','4 fillets, approximately 480–520 g',['Tuesday dinner'],'Workbook notes say a 2-pack, but four people need four fillets; buy two 2-packs. Freeze immediately and thaw Monday night.','fish',8,true,true,'Multipacks can be frozen on purchase for around 3 months; separate fillets before freezing if needed.'),
  item('Meat','Beef mince','500 g',['Spaghetti Bolognese'],'Enough for six portions when bulked with vegetables and tomatoes. Freeze on purchase and thaw Sunday night if the use-by date is short.','meat',4,true,true,'Larger value packs can be divided into 500 g portions and frozen for 3–4 months.'),
  item('Pantry','Tinned tomatoes','0 to buy; 2 pantry tins allocated',['Bolognese'],'Already available: 6 tins in pantry; allocate two and leave four in stock.','tinned goods',0,false,false,'At two tins per Bolognese, the remaining four tins cover two more batches and should last months unopened.'),
  item('Pantry','Tinned tuna','0 to buy; 2 pantry tins allocated',['Jacket potatoes','Tuesday lunch backup'],'Already available: 2 tins in pantry. Use one or two depending on leftover chicken quantity.','tinned goods',0,false,false,'Replace in 4–6 tin packs when discounted; unopened tins usually store for years, following the printed date.'),
  item('Pantry','Tinned baked beans','0 to buy; 2 pantry tins allocated',['Sunday lunch','Wednesday dinner','Thursday dinner'],'Already available: 2 tins. Use half-tins carefully across meals or buy one extra tin if the household prefers generous portions.','tinned goods',0,false,false,'Four-packs suit this plan and typically last 2–4 weeks.'),
  item('Pantry','Rice','0 to buy; pantry bag allocated',['Mackerel lunch'],'Already available: 1 bag in pantry.','rice and pasta',0,false,false,'A 2–5 kg bag is economical and may last 1–3 months if kept dry and airtight.'),
  item('Pantry','Dry pasta','0 to buy; approximately 500 g from pantry',['Bolognese'],'Already available: one assorted bag. Confirm at least 500 g remains before shopping.','rice and pasta',0,false,false,'Multipacks keep 1–2 years dry and are useful for regular Bolognese meals.'),
  item('Frozen','Breaded fish portions','0 to buy; 8–12 pantry portions allocated',['Thursday dinner'],'Already available: 1 bag. Confirm the bag contains enough portions for four people.','frozen',0,false,false,'Large freezer bags can last 1–2 months at one fish-finger meal per week.'),
  item('Frozen','Frozen chips','0 to buy; pantry bag allocated',['Friday dinner','Thursday dinner'],'Already available: 1 bag. Confirm it contains about 1.2–1.5 kg for both meals.','frozen',0,false,false,'A 1.5–2 kg bag is an efficient monthly buy if freezer space permits.'),
  item('Frozen','Frozen peas and vegetables','0 to buy; pantry bags allocated',['Mussels dinner','Mackerel rice','Roast dinner','Fish dinner'],'Already available: peas and a mixed vegetable bag.','frozen',0,false,false,'Family bags can cover 3–4 weeks and retain quality for months when tightly sealed.'),
  item('Frozen','Frozen chicken pieces','0 to buy; approximately 600 g allocated',['Chicken fajitas'],'Already available: 1 bag. Confirm at least 600 g remains.','frozen',0,false,false,'Buy larger bags only if portions are individually frozen; at one meal per week a 2 kg bag lasts about 3 weeks.'),
  item('Dairy','Cheese','0 to buy; pantry cheese allocated',['Beans on toast','Chicken sandwiches','Jacket potatoes'],'Already available: 2 wrapped packs in pantry.','dairy',0,true,false,'Grate and freeze surplus cheese for up to 2 months if it will not be used before its date.'),
  item('Chilled','Mayonnaise','0 to buy; pantry jar allocated',['Chicken lunches'],'Already available: 1 jar. Keep refrigerated after opening.','condiments',0,true,false,'One jar should last several weeks at this plan rate; avoid bulk buying opened chilled condiments.'),
  item('Snacks','Biscuits','1 pack',['Thursday snack'],'You already have Oreo biscuits and Belvita breakfast biscuits, so buy only one extra pack rather than the usual two.','biscuits',0.5,false,false,'Multipacks last several weeks unopened, but pantry stock means no large purchase is needed this week.'),
  item('Snacks','Crisps','1 six-pack',['Monday snack'],'A single multipack gives portion control.','snacks',2,false,false,'A 12–24 pack is economical if eaten weekly and kept dry; allow 2–4 weeks.'),
  item('Snacks','Cheddars','1 six-pack',['Tuesday snack'],'Matches the workbook quantity.','snacks',2,false,false,'Multipacks last several weeks unopened; buy only when on rotation to prevent snack overstock.'),
  item('Snacks','Oat bars','1 pack',['Backup snacks'],'Baby-friendly/organic as specified in the workbook.','snacks',2,false,false,'One box generally lasts 1–2 weeks depending on pack count.'),
  item('Snacks','Fruit lollies','1 pack',['Wednesday snack'],'Keep frozen.','frozen',2,false,false,'A standard multipack can last 2–4 weeks and is suitable for freezer bulk purchase.'),
  item('Household','Washing-up liquid','1 bottle',['Household essential'],'Routine non-food item from the workbook; check current stock before purchase.','household',2,false,false,'A large refill bottle can last 1–3 months and reduces packaging.'),
  item('Household','Toilet rolls','1 pack',['Household essential'],'Routine non-food item from the workbook; size the pack to storage space.','household',4,false,false,'A 9–12 roll pack commonly lasts 2–4 weeks for this household; larger packs are economical if dry storage is available.'),
  item('Household','Kitchen roll','1 two-roll pack',['Household essential'],'Routine non-food item from the workbook.','household',2,false,false,'A multi-roll pack may last 2–4 weeks; keep dry.')
];

const plan = {
  plan_name:'Seven-day low-waste family meal and shopping plan',
  week_start:'2026-09-11',
  people:4,
  assumptions:[
    'Shopping takes place Thursday 10 September 2026 and the seven-day plan runs Friday 11 September through Thursday 17 September 2026.',
    'The plan is sized for four people, the upper end of the stated 3–4-person range, except Thursday leftover lunch which explicitly provides two leftover portions plus pantry alternatives.',
    'Pantry quantities are copied from the workbook. Where the workbook gives no unit, a practical unit such as pack, tin, carton, jar or bag is inferred from the item name.',
    'The Pantry tab contains no use-by dates. To satisfy the schema, planning review dates are assigned: 13 September for highly perishable fresh items, 17 September for chilled/open items, 31 December 2026 for frozen items and 10 September 2027 for shelf-stable items. Check every printed date and override these assumptions.',
    'Workbook prices are used where listed for essentials, snacks and household products. Prices for meal-specific fresh ingredients are planning estimates in pounds and should be checked at the chosen shop.',
    'No allergies or dietary restrictions were supplied beyond soy milk and dairy-free weekly baking. Verify all labels, especially gluten-free needs suggested by the pantry food box.',
    'Items shown as 0 to buy are included in the shopping list to make pantry deductions explicit and must be quantity-checked before shopping.'
  ],
  days, weekly_preparations, pantry_inventory, shopping_list,
  estimated_total_cost: Number(shopping_list.reduce((s,x)=>s+x.estimated_price,0).toFixed(2)),
  waste_reduction_summary:[
    'Use pantry mussels, strawberries, grapes, sliced meat, wraps, hummus and chilled dairy first.',
    'Freeze salmon and beef mince on shopping day; freeze the chicken only if its use-by date does not cover Sunday.',
    'Freeze one sliced loaf immediately and remove only the slices needed.',
    'Cook a larger Sunday chicken and a six-portion Monday Bolognese so planned leftovers replace extra lunch purchases.',
    'Share carrots, celery, onions, potatoes and broccoli across multiple dinners and Wednesday soup.',
    'Freeze half the banana bread and cookies, plus surplus soup, to prevent snack and batch-cook waste.',
    'Check quantities in opened pantry bags before shopping; buy only the noted fallback item if stock is insufficient.'
  ]
};

fs.writeFileSync('meal_plan_2026-09-11.json', JSON.stringify(plan,null,2)+'\n');
